### ISSUE TITLE
網站的憑證過期

### ISSUE THREAD

**Issue by d2513850** [upupming/hit-gpa#3]
hit-gpa.space-hit.com 所顯示的憑證到2019‎年‎11‎月‎27‎日 ‎下午‎ ‎08‎:‎37‎:‎23過期
![憑證過期](https://user-images.githubusercontent.com/29460334/69848510-412bee00-12b5-11ea-98f5-bc72a0646024.png)

**Comment by upupming** [comment]
@d2513850 因为没钱服务器已经停机，你可以自己克隆到本地运行～
